export const TRANSCRIPT_DIMENSION_NAMES: Record<number, string> = {
  0: "Contemporary stand-up vs archaic scripted language",
  1: "Special-title and catalog metadata",
  2: "Core stand-up banter and conversational profanity",
  3: "Formal institutional language vs street vernacular",
  4: "Maher-style political current-events commentary",
  5: "Paul Mooney legacy political satire",
  6: "Dr Illinivich podiatrist sketch: fictional cast and dialogue",
  7: "Censored vs uncensored profanity: transcription artifact",
  8: "Eddie Murphy and Richard Pryor: classic stand-up legends",
  9: "AAVE-style hard-edged comic voice",
  10: "Sarah Silverman scratch-card prop-comedy bit",
  11: "Sarah Silverman persona in a mixed-comedian transcript",
  12: "Robbery and crime-story routine",
  13: "Daylight saving time conspiracy rant",
  14: "F-word-heavy delivery vs race and election discourse",
  15: "Profanity tokenization split: full forms vs censored fragments",
  16: "2020 US election and voter fraud comedy",
  17: "Dedicated bourbon and whiskey appreciation segment",
  18: "Medieval and fantasy scripted narration",
  19: "Bear and grizzly animal-encounter routine",
  20: "Israel–Palestine geopolitical and religious discourse",
  21: "Culture-war identity politics: liberal and antifa discourse",
  22: "Foreigner at a restaurant: Jewish identity and dining",
  23: "George Carlin: classic anti-establishment comedy",
  24: "Epstein files in a surreal domestic setting",
  25: "Religious family imagery: God, Mary and Christian symbolism",
  26: "Religious surreal blend: God and family absurdist imagery",
  27: "Cowboys and Indians: frontier history comedy",
  28: "Epstein and MBS elite-abuse scandal commentary",
  29: "Absurd musical spectacle: Salt-N-Pepa on a ship",
  30: "Gawain medieval fantasy: knightly atmospheric narration",
  31: "Wrestling and monster-show arena spectacle narration",
  32: "Conan O'Brien NRA and gun control commentary",
  33: "Ramy Youssef Arab-American Muslim identity comedy",
  34: "Child abuse and racism: shock-taboo dark comedy",
  35: "AAVE family storytelling with orangutan racial insult",
  36: "White privilege and oppression: social-justice meta-commentary",
  37: "Sexting and kink: explicit modern-relationship shock humour",
  38: "Burr-style podcast interview meta-commentary",
  39: "Ramy Youssef Muslim faith and current-events humour",
  40: "Crude domestic absurdity: laundry and vulgar language",
  41: "Everyday struggle: graduate poor-life explicit comedy",
  42: "Sexting and relationship-drama: kink-texting scene",
  43: "Election and guns: political rant podcast hybrid",
  44: "Trump-Russia collusion: casino and mafia scandal",
  45: "Motel housekeeping and service-work anecdotal comedy",
  46: "Awards and nominations: comedy-event celebrity commentary",
  47: "Celebrity and politics crossover: ballots and pop-culture",
  48: "War-history dictator comparisons: Hussein and Hitler",
  49: "Medieval French historical drama: Carrouges period-script",
  50: "Personal-name Israel-Palestine social identity discourse",
  51: "Bethlehem conquest framed as biblical magic trick",
  52: "Medieval French court: Carrouges and Le Gris script",
  53: "Government and Covid leadership: public-office crisis",
  54: "Historical-surreal named-entity blend: Last Duel meets contemporary",
  55: "Race and identity: Ryan Hamilton named-entity language",
  56: "Middle East war and politics: Saddam, Iran and refugees",
  57: "Moses and Pharaoh: Exodus metaphor in social commentary",
  58: "Immigration and asylum policy: migrants and border administration",
  59: "Jamie Foxx celebrity-surreal: pop-culture gossip and clones",
  60: "Jamie Foxx and Charlie Kirk celebrity-politics mashup",
  61: "Fragmented colloquial family dialogue: censored-token storytelling",
  62: "Heathers and pro-life mommies: domestic jury-room blend",
  63: "Covid government-response: crisis and pandemic leadership",
  64: "Israel, violence and guns: armed-conflict political discourse",
  65: "I Love Lucy sitcom domestic-life cluster",
  66: "I Love Lucy legal-drama crossover: classic TV courtroom",
  67: "I Love Lucy holiday-family: Christmas sitcom performance",
  68: "British slang and drug-talk: mum, GHB, youth culture",
  69: "Mushrooms, heaven and family: domestic existential comedy",
  70: "Science and genetics: observational routine with Scooby-Doo",
  71: "Jury trial and guns: courtroom justice and race",
  72: "Jury and social identity: quirky legal anecdote language",
  73: "Headmaster Perkins: school-authority institutional narrative",
  74: "Immigration and guns: asylum seekers in culture-war discourse",
  75: "Voting and ballots: civic-process election administration",
  76: "Indian and Asian identity: South Asian observational comedy",
  77: "Pride month and masks: pandemic and LGBTQ+ commentary",
  78: "Christmas and Santa: holiday-family nostalgia comedy",
  79: "Hijab, ISIS and Kanye: Muslim identity culture-war commentary",
  80: "School authority routine: Perkins headmaster institutional",
  81: "Culture-war celebrity: Helen, Kanye and hijab media blend",
  82: "Hijab and guns: Cruz vs Kimmel culture-war punditry",
  83: "Christmas and heaven: Santa and afterlife sentimental comedy",
  84: "Institutional authority meets culture war: headmaster and media",
  85: "Physical caricature: small-town characters and shock descriptors",
  86: "Kevin Hart and DoorDash: delivery-app urban comedy",
  87: "Awards season and social identity: nomination commentary",
  88: "Tobacco industry: Marlboro and PMI global brand commentary",
  89: "Surreal religious caricature: heaven and absurd physical comedy",
  90: "Ageing and bureaucracy: elderly licence-holder New York routine",
  91: "DoorDash and Arab-politician: delivery-driver identity routine",
  92: "Rural and southern character storytelling: Cletus and Eddie",
  93: "Planet, plastic and nihilism: Stanhope-style absurdist comedy",
  94: "Guns and constitution: mixed current-events political anecdote",
  95: "Gil and Ravi with Steely Dan: casual domestic banter",
  96: "Moonlight Oscar controversy: film-awards pop-culture commentary",
  97: "Valentine's Day romance and politics crossover",
  98: "Covid conspiracy theories: pandemic misinformation commentary",
  99: "Muslim identity in contemporary Britain: mosque and gig economy",
}

export const CHUNK_DIMENSION_NAMES: Record<number, string> = {
  0: "Core conversational stand-up language",
  1: "Gratitude and closing-performance: crowd-thanks banter",
  2: "Anecdotal family storytelling: mom and dad narration",
  3: "Racial and social commentary: Black and white identity",
  4: "Hard profanity and shock language: crude transgressive comedy",
  5: "Censored profanity fragments: split-token transcript artifact",
  6: "Family, kids and pets: domestic parenting comedy",
  7: "Gender and sexuality: men, women and gay social commentary",
  8: "Dog and pet observational comedy",
  9: "Family ageing and gender: parents and old-age observational",
  10: "Gay, race and family: social-identity observational comedy",
  11: "Dog, gay and women: small-scale social observational comedy",
  12: "Gay, masculinity and family: male identity and sexuality",
  13: "Gay, dog and friends: casual self-reflective social comedy",
  14: "Baby and family appearance: cute domestic observational comedy",
  15: "Gender and sex: domestic relationship argument language",
  16: "Ageing and gender: old-age observational stand-up voice",
  17: "God, family and relationships: spiritual-domestic comedy",
  18: "Belief, family and children: God and kids domestic humour",
  19: "Need and home: domestic situation-building anecdotal setup",
  20: "Crude body and age humour: shock-observational masculinity",
  21: "Old age, gay and family: general anecdotal transition",
  22: "Direct conversational questioning: interactive stand-up setup",
  23: "Small-talk observational banter: everyday stage storytelling",
  24: "Punchy anecdotal profanity: compact joke-story narration",
  25: "Direct opinion and assertion: short declarative comic voice",
  26: "Daily domestic routine: sleep, wife and day comedy",
  27: "Black identity and practical life: car, money and family",
  28: "Black identity, sex and feeling: personal social tension",
  29: "Food, home and night: house and eating observational comedy",
  30: "Sex, girls and confessional: personal sexual commentary",
  31: "Car, ageing and self-evaluation: status-and-feelings comedy",
  32: "Storytelling and lesson-giving: friends, wife and life narration",
  33: "Porn, phone and relationship: sexual-media anecdote",
  34: "City, car, phone and New York: urban mobility comedy",
  35: "Porn, sex and night: explicit nightlife conversational comedy",
  36: "New York, money and doctor: urban adult-life pressure",
  37: "Stuff, sex and car: adult-life observational routine",
  38: "Food, fat and work: eating and body-image self-assessment",
  39: "Mom, food, room and fat: family and body domestic routine",
  40: "Porn, phone, city and sex: digital vice urban comedy",
  41: "Dad, guys, fat and gun: masculine self-assessment language",
  42: "Talking, watching and doing: conversational everyday routine",
  43: "Phone, watch, job and money: modern daily-life habits",
  44: "Eating, talking and family: domestic chatter and home-life",
  45: "School, phone and sex: youthful modern daily-life commentary",
  46: "House, married, room and night: domestic married-home routine",
  47: "Eating, life and watching: lifestyle and habit daily routine",
  48: "Food, eating and Jesus: bodily habit and religious guilt",
  49: "Trump, fun and house: casual political and social banter",
  50: "Money, sex and insults: aggressive gendered social commentary",
  51: "Married life, status and slang: money and relationship talk",
  52: "Sleep, play and door: reflective existential everyday comedy",
  53: "Work, doctor, kids and apology: adult responsibility language",
  54: "Friends, money and fun: positive social routine",
  55: "Jesus, sleep and night: bedtime existential commentary",
  56: "Money, married, doctor and cat: settled-life adult comedy",
  57: "House, sex and men: adult domestic-sexual commentary",
  58: "School, friends and Jesus: growing-up social-development",
  59: "Family, home, money and funny: warm domestic observational",
  60: "Jesus, Trump and friends: belief-and-politics social identity",
  61: "Money, food and coffee: everyday habits and adult memory",
  62: "Friends, wife and conflict: relationship tension and friction",
  63: "Home, work, school and kid: domestic responsibility language",
  64: "School, work, hate and house: everyday frustration routine",
  65: "Trump, news, married and woman: relationship and politics overlap",
  66: "School, money and movie: growing-up youth-adult transition",
  67: "Friends, married and cat: urban friendship and domesticity",
  68: "Work, job, Trump and cats: labour-and-politics adult comedy",
  69: "Hate, years, women and kill: hostile relational rhetoric",
  70: "Weird, bad, fun and belief: everyday judgment commentary",
  71: "Room, money, doctor and Trump: constrained private-life stress",
  72: "Doctor, cat, house and fat: neurotic domestic problem-solving",
  73: "School, question, doctor and talk: curious conversational banter",
  74: "Country, America, work and hate: national frustration routine",
  75: "Water, gun, room and remember: domestic tension storytelling",
  76: "Night, job, money and way: reflective adult-life frustration",
  77: "School, family, death and crazy: dark interpersonal commentary",
  78: "Doctor, sleep, house and care: nighttime self-care routine",
  79: "Funny, person and laugh: comedy-meta humour evaluation",
  80: "Job, word, person and talking: social-performance commentary",
  81: "Question, trying, water and weird: curious awkwardness routine",
  82: "Trump, women and kill: sharp political-personal tension",
  83: "Believe, fun and dead: existential-comic life-and-death reflection",
  84: "Men, Trump, home and fun: masculine social commentary",
  85: "Doctor, wife, boy and crazy: marriage and relational introspection",
  86: "Gun, job, movie and play: masculine hobby and action routine",
  87: "Remember, question, song and play: reflective conversational banter",
  88: "Family, body, death and care: heavy emotional household tension",
  89: "Better, trying and Jesus: self-improvement and coping commentary",
  90: "Family, work, talking and play: domestic household conflict",
  91: "Cool, hell, dead and Trump: dark reactive observational comedy",
  92: "Doctor, home, Chinese and Indian: multicultural practical-life comedy",
  93: "Country, friend, porn and life: scattershot modern-life commentary",
  94: "World, job, gun and fun: assertive self-image social routine",
  95: "Wife, son, food and sleep: family-role household commentary",
  96: "Married, work, sorry and crazy: relationship repair and self-reflection",
  97: "Talking, sleep, movie and head: late-night bedtime drift",
  98: "Home, gun, problem and weird: defensive practical-life routine",
  99: "Trying, help, world and room: emotional struggle and coping",
}
