export const TRANSCRIPT_DIMENSION_NAMES: Record<number, string> = {
  0: "Modern Political and Topical Comedy vs Historical and Archaic Dialogue",
  1: "Special and Review Metadata vs OCR and Corrupted Text",
  2: "General Conversational Stand-Up",
  3: "Institutional and Medical Bureaucracy vs Raw Stand-Up",
  4: "Political Scandal Commentary",
  5: "Legacy-Comedian Tribute and Intellectual Satire",
  6: "Eccentric Character and Monologue Namescape",
  7: "Eddie Murphy Performance Cluster",
  8: "Fragmented Murphy Transcript Style",
  9: "Sound-Effect and Southern Character Bit",
  10: "Sarah Silverman Performance Cluster",
  11: "Silverman Robbery and Gun Bit",
  12: "Daylight-Saving and Household Robbery Bit",
  13: "Farm and Daylight-Saving Rant",
  14: "Profane Family Banter vs Electoral Slur-Politics",
  15: "Election and Trump Fraud Discourse",
  16: "Election and Black Identity Slang Cluster",
  17: "Bourbon and Whiskey Lifestyle Cluster",
  18: "Fantasy Script and Bourbon Hybrid",
  19: "Bear and Animal Story Bit",
  20: "Israel and Palestine Political Commentary",
  21: "Liberal Culture-War Commentary",
  22: "Immigrant Family and Restaurant Routine",
  23: "George Carlin Legacy Cluster",
  24: "Epstein and Miscellaneous Stage Narrative",
  25: "Religious Horror and Family Imagery",
  26: "Religious Surrealism and Epstein Contrast",
  27: "Cowboys and Indians Western Bit",
  28: "Epstein and Saudi Arabia Scandal Cluster",
  29: "Musical and Performance Variety Cluster",
  30: "Arthurian Fantasy Script Cluster",
  31: "Wrestling Entertainment Cluster",
  32: "Conan and Guns Commentary",
  33: "Racism and Child Molester Dark Humor Cluster",
  34: "Conan and Election Shock-Topic Blend",
  35: "Southern and Oklahoma Character Voice",
  36: "Bill Burr Race and Privilege Commentary",
  37: "Burr and Sexual and Election Edginess",
  38: "Working-Class Childhood Storytelling",
  39: "Ramy and Muslim Identity Cluster",
  40: "Crude British and Australian Slang Cluster",
  41: "Gun Rights and NRA Political Cluster",
  42: "Spy and Action Movie Script Cluster",
  43: "Russian Collusion and Trump Cluster",
  44: "Russia Scandal vs Election Counting",
  45: "Hotel and Housekeeping Race Bit",
  46: "Awards and Nomination Politics Cluster",
  47: "Historical European Drama Cluster",
  48: "Biblical and Historical Epic Blend",
  49: "Family Character Dialogue Cluster",
  50: "Middle East History and Identity Cluster",
  51: "The Last Duel and Medieval Nobility Cluster",
  52: "Government Crisis and Ryan Hamilton Cluster",
  53: "COVID and Renegotiation Political Theme",
  54: "Jamie Foxx Celebrity Cluster",
  55: "Jamie Foxx Personal Storytelling Cluster",
  56: "War on Terror Political Cluster",
  57: "Immigration and Jury System Cluster",
  58: "Border Administration Cluster",
  59: "Israel and Shootings Commentary",
  60: "Fragmented Political Slang Cluster",
  61: "Jimmy Kimmel and Late Night Cluster",
  62: "Pandemic Government Response Cluster",
  63: "Family Sitcom Character Cluster",
  64: "Absurd Domestic Future Theme",
  65: "I Love Lucy Cluster",
  66: "Holiday and Christianity Cluster",
  67: "Family Relationship Cluster",
  68: "Old Ladies and Electricity Bit",
  69: "Genetics and School and Family Theme",
  70: "Jury and TSA and Security Cluster",
  71: "School Discipline and FCC Cluster",
  72: "Kanye and Muslim and Identity Politics Cluster",
  73: "Gun Rights and Immigration Blend",
  74: "Election and Immigration Current Events Cluster",
  75: "Masks and Pride and Gender Politics Cluster",
  76: "Russell Peters Asian Identity Cluster",
  77: "Therapy and Hunger and Family Cluster",
  78: "Gender Conflict and Explicit Shock Cluster",
  79: "Hijab and Muslim Lifestyle Cluster",
  80: "Cultural Identity Commentary",
  81: "Breaking News Politics",
  82: "Holiday Family Storytelling",
  83: "Barroom Comic Persona",
  84: "Courtroom Absurdism",
  85: "Relationship Observations",
  86: "Aging Consumer Satire",
  87: "Celebrity Randomness Routine",
  88: "Product Shock Humor",
  89: "Cross-Cultural Identity Comedy",
  90: "Dry Persona Storytelling",
  91: "Time and Family Reflection",
  92: "Gun Rights Commentary",
  93: "Environmental Anxiety Humor",
  94: "Cultural Decline Satire",
  95: "Pandemic Delivery Economy",
  96: "Chaotic News Cycle",
  97: "Pop Culture Reference Humor",
  98: "Conspiracy Theory Satire",
  99: "Comic Book Villain Cluster",
  100: "Pop Politics Mashup",
  101: "Americana Storytelling",
  102: "Social Media Narcissism",
  103: "Civilizational Anxiety Humor",
  104: "Late Night Political Monologue",
  105: "Seasonal Political Chaos",
  106: "Brexit Commentary",
  107: "Sports Celebrity Romance",
  108: "Athlete Scandal Humor",
  109: "Populist Media Politics",
  110: "Supreme Court Politics",
  111: "Global Sports Identity",
  112: "Security Panic Humor",
  113: "Cultural Mashup Comedy",
  114: "Demographic Politics Humor",
  115: "Immigration Identity Humor",
  116: "Country Music Culture",
  117: "Nerd Shock Humor",
  118: "Asian Conspiracy Discourse",
  119: "Celebrity Travel Humor",
  120: "Legal Panic Satire",
  121: "Gender Identity Commentary",
  122: "Internet Radicalization Humor",
  123: "Musician Performance Culture",
  124: "Nationalist Weirdness Humor",
  125: "Institutional Paranoia Humor",
  126: "American Surrealism",
  127: "Ministerial Conspiracy Humor",
  128: "Diaspora Identity Commentary",
  129: "Regime Absurdism",
}

export const CHUNK_DIMENSION_NAMES: Record<number, string> = {
  0: "Core Stand-Up Language",
  1: "Crowd Appreciation Energy",
  2: "Family Storytelling",
  3: "Raw Profanity Persona",
  4: "Race and Identity Commentary",
  5: "Fragmented Profanity Speech",
  6: "Gender and Desire Commentary",
  7: "Parenting and Home Life",
  8: "Urgent Social Interaction",
  9: "Angry Social Commentary",
  10: "Childlike Playful Energy",
  11: "Pet Ownership Humor",
  12: "Edgy Identity Banter",
  13: "Family and Gender Reflection",
  14: "Marriage and Aging Commentary",
  15: "Male Insecurity Humor",
  16: "Emotional Validation Humor",
  17: "Everyday Vice Humor",
  18: "Belief and Masculinity Commentary",
  19: "Aging Male Reflection",
  20: "Body Image Humor",
  21: "Word Choice Commentary",
  22: "Midlife Social Humor",
  23: "Faith and Gender Commentary",
  24: "Neighborhood Life Humor",
  25: "Intimate Relationship Conflict",
  26: "Nightlife Persona",
  27: "Masculine Bravado Humor",
  28: "Race Relations Commentary",
  29: "Money and Materialism Humor",
  30: "Work Stress Humor",
  31: "Romantic Pursuit Humor",
  32: "Social Anxiety Humor",
  33: "Parenting Frustration Humor",
  34: "Political Irritation Humor",
  35: "Sexual Tension Humor",
  36: "Social Justice Commentary",
  37: "Edgy Debate Persona",
  38: "Childhood Memory Humor",
  39: "Faith Identity Humor",
  40: "Crude Shock Humor",
  41: "Gun Politics Commentary",
  42: "Action Movie Dialogue",
  43: "Russia Scandal Commentary",
  44: "Election Anxiety Humor",
  45: "Service Industry Humor",
  46: "Awards Show Commentary",
  47: "Historical Drama Dialogue",
  48: "Epic Narrative References",
  49: "Domestic Character Dialogue",
  50: "Religious Geopolitics Commentary",
  51: "Courtly Drama Dialogue",
  52: "Leadership Under Pressure",
  53: "Pandemic Era Frustration",
  54: "Celebrity Persona Commentary",
  55: "Recovery and Health Humor",
  56: "War on Terror Commentary",
  57: "Immigration Debate Humor",
  58: "Border Politics Humor",
  59: "Violence and Security Commentary",
  60: "Fragmented News Commentary",
  61: "Late Night TV Humor",
  62: "Emergency Government Response",
  63: "Sitcom Family Energy",
  64: "Surreal Family Absurdism",
  65: "Classic Sitcom References",
  66: "Holiday Tradition Humor",
  67: "Family Bond Commentary",
  68: "Aging and Household Humor",
  69: "Genetics and Family Traits",
  70: "Legal Process Humor",
  71: "Authority Figure Humor",
  72: "Culture War Commentary",
  73: "Security and Guns Commentary",
  74: "Polarized News Cycle",
  75: "Pride Era Social Commentary",
  76: "Cross-Cultural Accent Humor",
  77: "Emotional Need Humor",
  78: "Gender Conflict Satire",
  79: "Identity Performance Humor",
  80: "Celebrity Identity Commentary",
  81: "News Cycle Violence Humor",
  82: "Holiday Storytelling Comedy",
  83: "Rough Barroom Storytelling",
  84: "Surreal Courtroom Humor",
  85: "Relationship Persona Comedy",
  86: "Consumer Vice Humor",
  87: "Random Reference Comedy",
  88: "Dark Consumer Humor",
  89: "Global Identity Banter",
  90: "Dry Observational Persona",
  91: "Passing Time Commentary",
  92: "Gun Rights Satire",
  93: "Environmental Worry Humor",
  94: "Vice and Decline Humor",
  95: "Gig Economy Humor",
  96: "Chaotic Society Commentary",
  97: "Celebrity Reference Humor",
  98: "Conspiracy Satire",
  99: "Superhero Franchise Humor",
  100: "Election Pop Culture Mashup",
  101: "Regional Americana Humor",
  102: "Influencer Culture Satire",
  103: "Society in Decline Humor",
  104: "Late Night Monologue Style",
  105: "Holiday Politics Humor",
  106: "Brexit Commentary",
  107: "Sports Celebrity Humor",
  108: "Athlete Tabloid Humor",
  109: "Populist Media Commentary",
  110: "Judiciary Power Commentary",
  111: "Global Sports Banter",
  112: "Security Panic Satire",
  113: "Heritage Mashup Humor",
  114: "Demographic Politics Satire",
  115: "Immigration Shock Humor",
  116: "Music Industry Humor",
  117: "Geek Shock Humor",
  118: "Global Conspiracy Humor",
  119: "Celebrity Travel Banter",
  120: "Conspiracy Court Satire",
  121: "Gender Identity Humor",
  122: "Fringe Internet Politics",
  123: "Musician Life Comedy",
  124: "Nationalist Weirdness Satire",
  125: "Institutional Fear Humor",
  126: "Everyday Surrealism",
  127: "Political Rumor Satire",
  128: "Diaspora Identity Humor",
  129: "Government Vice Satire",
}
